Comment out model_output build due to error - @usr110
I think your updatest to model_output cause this:

Error: could not find function "add_table_style"